// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations/introspecção precisam da conexão direta (sem pgbouncer) do Neon.
    // A aplicação em runtime usa DATABASE_URL (pooler) via PrismaService/adapter-pg.
    url: process.env["DIRECT_URL"],
  },
});
